
import React from 'react';

export default props => {
    return (
        <div>
            <h1>Gifts & Parties</h1>
            <p>GIFTSANDPARTIESANDGIFTSANDPARTIESANDGIFTSANDPARTIESANDGIFTSANDPARTIESANDGIFTSANDPARTIESANDGIFTSANDPARTIESANDGIFTSAND PARTIESANDGIFTSANDPARTIESANDGIFTSANDPARTIESANDGIFTSANDPARTIESANDGIFTSANDPARTIESANDGIFTSANDPARTIESANDGIFTSANDPARTIESAND GIFTSANDPARTIESANDGIFTSANDPARTIESANDGIFTSANDPARTIESANDGIFTSANDPARTIESANDGIFTSANDPARTIESANDGIFTSANDPARTIESANDGIFTS</p>
        </div>
    );
}
